import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Link from "next/link";
import "./globals.css";
import { ErrorWrapper } from "./error-wrapper";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: {
    default: "Routing Demo - AIS",
    template: "%s | AIS",
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header style={{ backgroundColor: "lightgray", padding: "1rem" }}>
          <div>My App</div>
          <Link href="/">
            <div>Home</div>
          </Link>
        </header>
        <div style={{ backgroundColor: "", padding: "2rem" }}>
          {/* <ErrorWrapper>{children}</ErrorWrapper> */}
          {children}
        </div>
        <footer style={{ backgroundColor: "lightgray", padding: "1rem" }}>
          <p>© 2026 My App</p>
        </footer>
      </body>
    </html>
  );
}
